Refactor
husarion/gazebo_worlds pull request #6
Opened 2024-04-30 13:18 UTC by rafal-gorecki

- Clean up: Delete unnecessary files, reduce size from 63 MB to 28 MB
- husarion_office.sdf: fix to work with gz Fortress and delete sensors from rosbot (some of them doesn't work and no need to simulate imu on static rosbot)
- new launch file with some useful params

**IMPORTANT**
After merge please merge also following branches:
- [panther_ros](https://github.com/husarion/panther_ros/pull/300)
- [rosbot_xl_ros](https://github.com/husarion/rosbot_xl_ros/pull/67)
- [rosbot_ros](https://github.com/husarion/rosbot_ros/pull/107)
- [rosbot_xl_manipulation](https://github.com/husarion/rosbot_xl_manipulation_ros/pull/8)

2024-05-06 11:02 UTC, pawelirh requested changes

2024-05-06 11:02 UTC, pawelirh commented on CMakeLists.txt
>  find_package(ament_cmake REQUIRED)
Please add a `.gitignore` file. (It may be standard one from our repositories, the goal here is to ignore .vscode/ files)

2024-05-06 11:02 UTC, pawelirh commented on worlds/meshes/husarion_world.dae
The name of this file suggests it is a world while it's not
1. How about naming it `husarion_logo.dae`
2. I'd propose treating it as a model without additional configuration files and sticking to the pattern (create a directory (`/models/husarion_logo/meshes/husarion_logo.dae`) in the `models` folder and move it there )

2024-05-06 11:02 UTC, pawelirh commented on worlds/models/ConfTable/meshes/ConfTable2.stl
APPLIES TO THE WHOLE REPO

My suggestion is to flatten the repository structure and move the `models` folder to the root so we distinguish two directories there `models` and `worlds`.

2024-05-06 11:02 UTC, pawelirh commented on worlds/models/ConfTable/meshes/ConfTable2.stl
APPLIES TO THE WHOLE REPO

Please standardize the naming convention of directories and files. The most natural approach would be to use everywhere `snake_case`

2024-05-06 11:02 UTC, pawelirh commented on worlds/models/ConfTable/meshes/ConfTable2.stl
APPLIES TO THE WHOLE REPO

Please format all xml files

2024-05-06 11:02 UTC, pawelirh commented on worlds/models/ConfTable/meshes/ConfTable2.stl
I propose renaming this file and directory  to simply `conference_table`

2024-05-06 11:02 UTC, pawelirh commented on worlds/husarion_world.sdf
I'd consider here renaming this world to `husarion_logo` so we exactly know what to expect

2024-05-06 11:02 UTC, pawelirh commented on CMakeLists.txt
I believe we depend on some gazebo plugins here and `launch-ros`. Could you specify the proper dependency?

2024-05-06 11:02 UTC, pawelirh commented on CMakeLists.txt
TIHS APPLIES TO `package.xml`

- Let's change the maintainer, may be as follows
```xml
  <author email="pawel.kowalski@husarion.com">Pawel Kowalski</author>
  <maintainer email="support@husarion.com">Husarion</maintainer>
```
- This package is not dependent on rclcpp
- Specify missing dependencies (same as in cmake)

2024-05-06 11:02 UTC, pawelirh commented on README.md
A few aspects regarding the readme:
- please use a template from other repositories with proper sections highlighted (separate for building and launching)
- would be nice to have listed launch arguments 
- would be nice to have available worlds listed with descriptions and proper visualization images 
- please format readme file

2024-05-06 12:10 UTC, pawelirh commented on launch/gz_sim.launch.py
Please format this file with python black formatted (Husarion standard)

2024-05-06 14:34 UTC, rafal-gorecki commented on worlds/models/ConfTable/meshes/ConfTable2.stl
Rename to ConferenceTable

2024-05-07 13:08 UTC, pawelirh requested changes

2024-05-07 13:08 UTC, pawelirh commented on README.md
> +- `husarion_world.sdf` - World representing our logo.
How about displaying worlds visualization just under they're listed?

```suggestion
- `empty_with_plugins.sdf` - Empty world with attached plugins necessary for the proper operation of our robots.
- `husarion_office.sdf` - World resembling the office we work in.
  <p align="center">
    <img width="460" height="300" src="./images/office1.png">
    <img width="460" height="300" src="./images/office2.png">
  </p>
- `husarion_world.sdf` - World representing our logo.
  <p align="center">
    <img width="460" height="300" src="./images/husarion_world.png">
  </p>
```

2024-05-07 13:08 UTC, pawelirh commented on README.md
>  ![img3](./images/husarion_world.png)
If the suggestion above is accepted, this section is no longer needed.

2024-05-07 13:08 UTC, pawelirh commented on README.md
> +| ARGUMENTS         | DESCRIPTION                                                                                                  | VALUE                                                      |
VALUE -> DEFAULT VALUE

2024-05-07 13:08 UTC, pawelirh commented on CMakeLists.txt
Still missing `find_package()` in cmake

2024-05-07 13:12 UTC, pawelirh commented on worlds/models/ConfTable/meshes/ConfTable2.stl
Still not consistent:
- meshes file names are both `snake_case` and `PascalCase`
- why don't use `snake_case` for models directories as well? Creating and adding a new model we don't need to hesitate and check how this directory is typed 🤔

2024-05-08 06:36 UTC, rafal-gorecki commented on CMakeLists.txt
is not needed is exec_depend not build_depend

2024-05-08 06:41 UTC, rafal-gorecki commented on README.md
> +- `husarion_world.sdf` - World representing our logo.
imo, people want to run things more often than to see the results, so with this logic I would leave what a person might reach for most often at the very top. However, I added captions for the photos.

2024-05-08 09:28 UTC, pawelirh approved these changes

2024-05-08 09:34 UTC, merged